config/routes.rb
Memleak::Engine.routes.draw do

  root to: 'memleak#index'

  resources :snapshots

end

app/models/memory_snapshot.rb
class MemorySnapshot < ActiveRecord::Base

  scope :between, -> from, to { where('id >= ? AND id <= ?', from, to) }

  serialize :allocated_memory_by_gem, Array
  serialize :allocated_objects_by_gem, Array
  serialize :retained_memory_by_gem, Array
  serialize :retained_objects_by_gem, Array
  serialize :allocated_memory_by_file, Array
  serialize :allocated_objects_by_file, Array
  serialize :retained_memory_by_file, Array
  serialize :retained_objects_by_file, Array
  serialize :allocated_memory_by_location, Array
  serialize :allocated_objects_by_location, Array
  serialize :retained_memory_by_location, Array
  serialize :retained_objects_by_location, Array
  serialize :allocated_memory_by_class, Array
  serialize :allocated_objects_by_class, Array
  serialize :retained_memory_by_class, Array
  serialize :retained_objects_by_class, Array

end

app/controllers/memleak/application_controller.rb
module Memleak
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/memleak/memleak_controller.rb
module Memleak
  class MemleakController < ApplicationController

    def index
      @memory_snapshots = MemorySnapshot.all
    end

  end
end

app/controllers/memleak/snapshots_controller.rb
module Memleak
  class SnapshotsController < ApplicationController

    def index
      render json: get_memory_snapshots
    end

    def show
      @snapshot = MemorySnapshot.find params[:id]
    end

    private

    def get_memory_snapshots
      from, to = snapshots_params[:snapshots_from], snapshots_params[:snapshots_to]

      if from and to
        MemorySnapshot.between from, to
      else
        MemorySnapshot.all
      end
    end

    def snapshots_params
      params.permit :snapshots_from, :snapshots_to
    end

  end
end

app/helpers/memleak/application_helper.rb
module Memleak
  module ApplicationHelper

    def snapshot_request(snapshot) 
      "#{snapshot.controller}##{snapshot.action}"
    end

    def format_time(time)
      time.strftime '%d %b %H:%M'
    end

  end
end

app/views/layouts/memleak/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Memleak</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <%= stylesheet_link_tag    "memleak/application", media: "all" %>
  <%= javascript_include_tag "memleak/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="memleak"></div>
  <%= yield %>

</body>
</html>

app/views/memleak/memleak/index.slim
header
  h1 Dashboard

#chart.chart

table
  thead
    tr
      th id
      th Controller#action
      th Total allocated objects
      th Total allocated memsize
      th Total retained objects
      th Total retained memsize
      th Created At

  tbody
    - @memory_snapshots.each do |snapshot|
      tr
        td = link_to "##{snapshot.id}", snapshot_path(snapshot)
        td = snapshot_request snapshot
        td = snapshot.total_allocated_objects
        td = snapshot.total_allocated_memsize
        td = snapshot.total_retained_objects
        td = snapshot.total_retained_memsize
        td = format_time snapshot.created_at

app/views/memleak/snapshots/show.slim
h1 Snapshot #{@snapshot.id} 

table
  tr
    td Action
    td = @snapshot.action

  tr
    td Controller
    td = @snapshot.controller

  tr
    td Total_allocated_objects
    td = @snapshot.total_allocated_objects

  tr
    td Total_allocated_memsize
    td = @snapshot.total_allocated_memsize

  tr
    td Total_retained_objects
    td = @snapshot.total_retained_objects

  tr
    td Total_retained_memsize
    td = @snapshot.total_retained_memsize

  tr
    td Allocated_memory_by_gem
    td
      - @snapshot.allocated_memory_by_gem.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Allocated_objects_by_gem
    td
      - @snapshot.allocated_objects_by_gem.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Retained_memory_by_gem
    td
      - @snapshot.retained_memory_by_gem.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Retained_objects_by_gem
    td
      - @snapshot.retained_objects_by_gem.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Allocated_memory_by_file
    td
      - @snapshot.allocated_memory_by_file.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Allocated_objects_by_file
    td
      - @snapshot.allocated_objects_by_file.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Retained_memory_by_file
    td
      - @snapshot.retained_memory_by_file.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Retained_objects_by_file
    td
      - @snapshot.retained_objects_by_file.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Allocated_memory_by_location
    td
      - @snapshot.allocated_memory_by_location.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Allocated_objects_by_location
    td
      - @snapshot.allocated_objects_by_location.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Retained_memory_by_location
    td
      - @snapshot.retained_memory_by_location.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Retained_objects_by_location
    td
      - @snapshot.retained_objects_by_location.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Allocated_memory_by_class
    td
      - @snapshot.allocated_memory_by_class.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Allocated_objects_by_class
    td
      - @snapshot.allocated_objects_by_class.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Retained_memory_by_class
    td
      - @snapshot.retained_memory_by_class.each do |s|
        p = "#{s[:data]} - #{s[:count]}"

  tr
    td Retained_objects_by_class
    td
      - @snapshot.retained_objects_by_class.each do |s|
        p = "#{s[:data]} - #{s[:count]}"